version: "3.3"

services:

  provider:
    image: "antonboom/lines-provider"
    ports:
      - 8000:8000

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379


  #main:
    #build:
     # context: .
      #dockerfile: build/Dockerfile

    #depends_on:
     # - redis


