version: "3.3"

services:

  provider:
    image: "antonboom/lines-provider"

  redis:
    image: "redis:alpine"


  main:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 8001:8001
      - 8002:8002
    depends_on:
      - provider
      - redis


