name: testTask build

on:
  push:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          args: -c .golangci.yml

  tests:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - uses: actions/checkout@v1
      - name: running tests
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v1
      - name: building
        run: make build
