name: testTask build

on:
  push:
    branches: [ master ]

jobs:
  lints:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        run: make lint

  tests:
    runs-on: ubuntu-latest
    needs: lints
    steps:
      - uses: actions/checkout@v1
      - name: running tests
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v1
      - name: building
        run: make build
